### PR TITLE
Add config option for logging full paths

### PR DESCRIPTION
**Pull request by stavros-wb**

### CODE REVIEW

**Review by SokratisVidros — APPROVED** [review]
🎖

**Review by nikostoulas — APPROVED** [review]

**Comment by SokratisVidros** [comment]
@nikostoulas who issues new versions of this in the post-matz era?

**Comment by nikostoulas** [comment]
@SokratisVidros I also have access

**Comment by nikostoulas** [comment]
But we have also added riviere to the organization.  Let's move the next versions there. See Matzavinos last commit: https://github.com/Workable/riviere/commit/ae7f144678ffd74ae04c1e07582eeedbe98a3285

**Comment by SokratisVidros** [comment]
Perfect, so everyone can publish then. @stavros-wb you can proceed with the publishing!

**Pull request merged**
